//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANUNCIOS_ENVIADOS
    {
        public int ID_Anuncios_Enviados { get; set; }
        public int ID_Anuncios { get; set; }
        public int ID_Cliente { get; set; }
        public byte[] Fecha { get; set; }
    
        public virtual ANUNCIOS ANUNCIOS { get; set; }
        public virtual CLIENTES CLIENTES { get; set; }
    }
}
