//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTICULOS_PROVEEDOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ARTICULOS_PROVEEDOR()
        {
            this.SOLICITUD_ARTICULOS = new HashSet<SOLICITUD_ARTICULOS>();
        }
    
        public int ID_Articulos_Proveedor { get; set; }
        public int ID_Proveedor { get; set; }
        public int ID_Articulos { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ARTICULOS ARTICULOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOLICITUD_ARTICULOS> SOLICITUD_ARTICULOS { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
    }
}
