//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAMPA_AS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAMPA_AS()
        {
            this.CAMPA_AS_PARTICIPANTES = new HashSet<CAMPA_AS_PARTICIPANTES>();
        }
    
        public int ID_Campa_as { get; set; }
        public string Nombre { get; set; }
        public System.DateTime Fecha_Inicio { get; set; }
        public System.DateTime Fecha_Fin { get; set; }
        public string Cantidad_Pacientes { get; set; }
        public int ID_Distritos { get; set; }
        public string Descripcion { get; set; }
        public int Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAMPA_AS_PARTICIPANTES> CAMPA_AS_PARTICIPANTES { get; set; }
        public virtual ESTADOS ESTADOS { get; set; }
        public virtual DISTRITOS DISTRITOS { get; set; }
    }
}
