//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENTES()
        {
            //this.ANUNCIOS_ENVIADOS = new HashSet<ANUNCIOS_ENVIADOS>();
            //this.CAMPA_AS_PARTICIPANTES = new HashSet<CAMPA_AS_PARTICIPANTES>();
            //this.FACTURAS = new HashSet<FACTURAS>();
            //this.MASCOTAS = new HashSet<MASCOTAS>();
        }
        
        public int ID_Cliente { get; set; }
        public string Cedula { get; set; }
        public string Nombre { get; set; }
        public string Apellido_1 { get; set; }
        public string Apellido_2 { get; set; }
        public string Correo { get; set; }
        public string Telefono { get; set; }
        public int ID_Provincias { get; set; }
        public int ID_Cantones { get; set; }
        public int ID_Distritos { get; set; }
        public string Direccion { get; set; }
        public int Credito { get; set; }
        public int Estado { get; set; }
    
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<ANUNCIOS_ENVIADOS> ANUNCIOS_ENVIADOS { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<CAMPA_AS_PARTICIPANTES> CAMPA_AS_PARTICIPANTES { get; set; }
        //public virtual CANTONES CANTONES { get; set; }
        //public virtual ESTADOS ESTADOS { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<FACTURAS> FACTURAS { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<MASCOTAS> MASCOTAS { get; set; }
        ////public virtual DISTRITOS DISTRITOS { get; set; }
        //public virtual PROVINCIAS PROVINCIAS { get; set; }
    }
}
