//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class CREDITOS
    {
        public int ID_Creditos { get; set; }
        public int ID_Factura { get; set; }
        public Nullable<decimal> Monto_Anterior { get; set; }
        public Nullable<decimal> Monto_Actual { get; set; }
    
        public virtual FACTURAS FACTURAS { get; set; }
    }
}
