//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_SERVICIO
    {
        public int ID_Detalle_Servicio { get; set; }
        public int ID_Factura { get; set; }
        public int ID_Servicios { get; set; }
        public int ID_Cita { get; set; }
        public Nullable<int> Cantidad { get; set; }
    
        public virtual CITAS CITAS { get; set; }
        public virtual FACTURAS FACTURAS { get; set; }
        public virtual SERVICIOS SERVICIOS { get; set; }
    }
}
