//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA_PROMOCION
    {
        public int ID_Factura_Promocion { get; set; }
        public int ID_Promocion { get; set; }
        public int ID_Factura { get; set; }
    
        public virtual FACTURAS FACTURAS { get; set; }
        public virtual PROMOCIONES PROMOCIONES { get; set; }
    }
}
