//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FACTURAS()
        {
            this.COBROS = new HashSet<COBROS>();
            this.CREDITOS = new HashSet<CREDITOS>();
            this.DESPACHO = new HashSet<DESPACHO>();
            this.DETALLE_ARTICULOS = new HashSet<DETALLE_ARTICULOS>();
            this.DETALLE_SERVICIO = new HashSet<DETALLE_SERVICIO>();
            this.FACTURA_PROMOCION = new HashSet<FACTURA_PROMOCION>();
            this.SERVICIOS_EXPRESS = new HashSet<SERVICIOS_EXPRESS>();
        }
    
        public int ID_Facturas { get; set; }
        public int ID_Cliente { get; set; }
        public int ID_Caja { get; set; }
        public int Numero_Factura { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Descripcion { get; set; }
        public decimal Total { get; set; }
        public byte Tipo_Pago { get; set; }
        public int Estado { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COBROS> COBROS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CREDITOS> CREDITOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DESPACHO> DESPACHO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_ARTICULOS> DETALLE_ARTICULOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_SERVICIO> DETALLE_SERVICIO { get; set; }
        public virtual ESTADOS ESTADOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURA_PROMOCION> FACTURA_PROMOCION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICIOS_EXPRESS> SERVICIOS_EXPRESS { get; set; }
        public virtual TIPO_PAGO TIPO_PAGO1 { get; set; }
    }
}
