//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA_COMPRA
    {
        public int ID_Factura_Compra { get; set; }
        public int ID_Solicitud_Compra { get; set; }
        public int Numero_Factura { get; set; }
        public string Referencia_Bancaria { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Descripcion { get; set; }
        public decimal Total { get; set; }
    
        public virtual SOLICITUD_COMPRA SOLICITUD_COMPRA { get; set; }
    }
}
