//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INVENTARIO()
        {
            this.DETALLE_ARTICULOS = new HashSet<DETALLE_ARTICULOS>();
        }
    
        public int ID_Inventario { get; set; }
        public int ID_Articulos { get; set; }
        public decimal Cantidad { get; set; }
        public int Estado { get; set; }
    
        public virtual ARTICULOS ARTICULOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_ARTICULOS> DETALLE_ARTICULOS { get; set; }
        public virtual ESTADOS ESTADOS { get; set; }
    }
}
