//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOMINA_PERSONAL
    {
        public int ID_Nomina_Personal { get; set; }
        public int ID_Nomina { get; set; }
        public int ID_Personal { get; set; }
        public Nullable<decimal> Total_Horas { get; set; }
        public Nullable<decimal> Salario_Bruto { get; set; }
        public Nullable<decimal> Salario_Neto { get; set; }
    
        public virtual NOMINA NOMINA { get; set; }
        public virtual PERSONAL PERSONAL { get; set; }
    }
}
