//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBSERVACIONES
    {
        public int ID_Observaciones { get; set; }
        public int ID_Cita { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime CreateAt { get; set; }
    
        public virtual CITAS CITAS { get; set; }
    }
}
