//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARTICIPANTES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PARTICIPANTES()
        {
            this.PRUEBAS_PARTICIPANTES = new HashSet<PRUEBAS_PARTICIPANTES>();
            this.REQUISITOS_PARTICIPANTES = new HashSet<REQUISITOS_PARTICIPANTES>();
        }
    
        public int ID_Participantes { get; set; }
        public int ID_Reclutamiento { get; set; }
        public string Cedula_ { get; set; }
        public string Nombre { get; set; }
        public string Apellido_1 { get; set; }
        public string Apellido_2 { get; set; }
        public string Correo { get; set; }
        public string Telefono { get; set; }
        public int ID_Provincia { get; set; }
        public int ID_Canton { get; set; }
        public int ID_Distrito { get; set; }
        public string Direccion { get; set; }
        public int Estado { get; set; }
    
        public virtual ESTADOS ESTADOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRUEBAS_PARTICIPANTES> PRUEBAS_PARTICIPANTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REQUISITOS_PARTICIPANTES> REQUISITOS_PARTICIPANTES { get; set; }
        public virtual RECLUTAMIENTO RECLUTAMIENTO { get; set; }
    }
}
