//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRUEBAS_PARTICIPANTES
    {
        public int ID_Pruebas_Participantes { get; set; }
        public int ID_Pruebas { get; set; }
        public int ID_Participantes { get; set; }
        public int Nota { get; set; }
    
        //public virtual PARTICIPANTES PARTICIPANTES { get; set; }
        //public virtual PRUEBAS PRUEBAS { get; set; }
    }
}
