//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLICITUD_ARTICULOS
    {
        public int ID_Solicitud_Articulos { get; set; }
        public int ID_Articulo_Proveedor { get; set; }
        public int ID_Solicitud_Compra { get; set; }
        public string Descripcion { get; set; }
        public decimal Cantidad { get; set; }
    
        //public virtual ARTICULOS_PROVEEDOR ARTICULOS_PROVEEDOR { get; set; }
        //public virtual SOLICITUD_COMPRA SOLICITUD_COMPRA { get; set; }
    }
}
