//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO_ROL
    {
        public int ID_Usuario_Rol { get; set; }
        public int ID_Usuario { get; set; }
        public int ID_Roles { get; set; }
    
        public virtual ROLES ROLES { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
