ALTER TABLE PERSONAL ADD  ID_Provincia			INT					 NULL;
ALTER TABLE PERSONAL ADD  ID_Canton			INT					 NULL;
ALTER TABLE PERSONAL ADD  ID_Distrito			INT					 NULL;
ALTER TABLE PERSONAL ADD  Direccion		        VARCHAR (150)       NULL;

ALTER TABLE PERSONAL
ADD CONSTRAINT FK_ProvinciaPersonal
FOREIGN KEY (ID_Provincia) REFERENCES PROVINCIAS(ID_Provincias);

ALTER TABLE PERSONAL
ADD CONSTRAINT FK_CantonesPersonal
FOREIGN KEY (ID_Canton) REFERENCES CANTONES(ID_Cantones);

ALTER TABLE PERSONAL
ADD CONSTRAINT FK_DistritosPersonal
FOREIGN KEY (ID_Distrito) REFERENCES DISTRITOS(ID_Distritos);

ALTER TABLE PARTICIPANTES
ADD CONSTRAINT FK_ProvinciaParticipantes
FOREIGN KEY (ID_Provincia) REFERENCES PROVINCIAS(ID_Provincias);

ALTER TABLE PARTICIPANTES
ADD CONSTRAINT FK_CantonesParticipantes
FOREIGN KEY (ID_Canton) REFERENCES CANTONES(ID_Cantones);

ALTER TABLE PARTICIPANTES
ADD CONSTRAINT FK_DistritosParticipantes
FOREIGN KEY (ID_Distrito) REFERENCES DISTRITOS(ID_Distritos);